general {
    hide_cursor = true
}

background {
    monitor =
    path = $HOME/.config/hypr/lockScreenWallpaper.png
	blur_passes = 4
	blur_size = 2
    brightness = 0.2
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(ffffffee)
    check_color = rgba(8cbeffee)
    fail_color = rgba(ff6e6eee)

    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 4

    placeholder_text = Input password...

    # uncomment if you wish to display a message during authentication
    # check_text = Authenticating...

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = 0, 200
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, 300
    halign = center
    valign = center
}
