position: "top"
height: 21
margin.top: 4
margin.left: 10
margin.right: 10
popup_gap: 2

start:
  - type: "workspaces"

center:
  - type: "cairo"
    icons: true
    titles: false
    group_by: "app_id"

end:
  - type: "clock"