MAPPINGS:
  - KEY: KEY_CAPSLOCK
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_I
    WITH: KEY_CAPSLOCK
    SEND: KEY_UP

  - KEY: KEY_J
    WITH: KEY_CAPSLOCK
    SEND: KEY_LEFT

  - KEY: KEY_K
    WITH: KEY_CAPSLOCK
    SEND: KEY_DOWN

  - KEY: KEY_L
    WITH: KEY_CAPSLOCK
    SEND: KEY_RIGHT

  - KEY: KEY_U
    WITH: KEY_CAPSLOCK
    SEND: KEY_PAGEUP

  - KEY: KEY_H
    WITH: KEY_CAPSLOCK
    SEND: KEY_PAGEDOWN

  - KEY: KEY_X
    WITH: KEY_CAPSLOCK
    SEND: KEY_CUT

  - KEY: KEY_C
    WITH: KEY_CAPSLOCK
    SEND: KEY_COPY

  - KEY: KEY_V
    WITH: KEY_CAPSLOCK
    SEND: KEY_PASTE

  - KEY: KEY_F
    WITH: KEY_CAPSLOCK
    SEND: KEY_LEFTSHIFT