
[indicator]
padding = { open = "▐", close = "▌" }

[status]
overall   = {}
sep_left  = { open = "▐", close = "▌" }
sep_right = { open = "▐", close = "▌" }

[mode]
normal_main = { fg = "#010101", bg = "#78A9FF", bold = true }
normal_alt  = { fg = "#F2F4F8", bg = "#25334D" }

# Select mod
select_main = { fg = "#010101", bg = "#BE95FF", bold = true }
select_alt  = { fg = "#F2F4F8", bg = "#3A2D4D" }

# Unset mod
unset_main = { fg = "#010101", bg = "#25BE6A", bold = true }
unset_alt  = { fg = "#F2F4F8", bg = "#0C3A21" }

[tabs]
active   = { fg = "#010101", bg = "#78A9FF", bold = true }
inactive = { fg = "#F2F4F8", bg = "#25334D" }

sep_inner  = { open = "▐", close = "▌" }
sep_outer = { open = "", close = "" }
