# etc/intercept-remap.yaml
MAPPINGS:
  - KEY: KEY_CAPSLOCK
    HOLD: LAYER_NAV

LAYERS:
  LAYER_NAV:
    KEY_J: KEY_LEFT
    KEY_K: KEY_DOWN
    KEY_I: KEY_UP
    KEY_L: KEY_RIGHT
    KEY_U: KEY_PAGEUP
    KEY_H: KEY_PAGEDOWN
    KEY_X: [KEY_LEFTCTRL, KEY_X]
    KEY_C: [KEY_LEFTCTRL, KEY_C]
    KEY_V: [KEY_LEFTCTRL, KEY_V]
    KEY_F: KEY_LEFTSHIFT
